server:
  port: 9999
zuul:
  ignoredServices: '*'
  routes:
    microservice-a:
      path: /micro-a/**
      serviceId: microservice-a
    microservice-b:
      path: /micro-b/**
      serviceId: microservice-b

management:
  endpoints:
    web:
      exposure:
        include: '*'