server:
  port: 9999
zuul:
  ignoredServices: '*'
  routes:
    microservice-a:
      path: /micro-a/**
      serviceId: microservice-a
    microservice-b:
      path: /micro-b/**
      serviceId: microservice-b

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: prod
zuul:
  routes:
    microservice-a:
      path: /micro-a/**
      serviceId: service-a
      url: http://service-a:8081/microservice-a/
    microservice-b:
      path: /micro-b/**
      serviceId: service-b
      url: http://service-b:8082/microservice-b/